export const lessons = [
  { section: "Classes", slug: "01-classes", title: "Classes & Objects", blurb: "Recap: classes, objects, instance vs static members." },
  { section: "Classes", slug: "02-constructors", title: "Constructors", blurb: "Constructors, overloading, this(), and object initializers." },
  { section: "Classes", slug: "03-methods", title: "Methods", blurb: "Overloading, params, ref, out, and the TryX pattern." },
  { section: "Classes", slug: "04-access-modifiers", title: "Fields & Access", blurb: "readonly fields, public vs private, and encapsulation." },
  { section: "Classes", slug: "05-properties", title: "Properties & Indexers", blurb: "Auto-properties, init, required, computed values, and indexers." },
  { section: "Associations", slug: "06-inheritance", title: "Inheritance", blurb: "Reuse code with an is-a relationship." },
  { section: "Associations", slug: "07-composition", title: "Composition", blurb: "Build objects from parts with a has-a relationship." },
  { section: "Inheritance Deep Dive", slug: "08-protected-base", title: "protected & base", blurb: "protected, internal, and calling base constructors." },
  { section: "Inheritance Deep Dive", slug: "09-casting", title: "Casting & Boxing", blurb: "Upcasting, downcasting, is, as, and boxing." },
  { section: "Polymorphism", slug: "10-polymorphism", title: "Method Overriding", blurb: "virtual and override: one call, many behaviors." },
  { section: "Polymorphism", slug: "11-abstract-sealed", title: "Abstract & Sealed", blurb: "Force subclasses to implement, or stop inheritance." },
  { section: "Interfaces", slug: "12-interfaces", title: "Interfaces", blurb: "Contracts a class promises to fulfill." },
  { section: "Interfaces", slug: "13-dependency-injection", title: "Dependency Injection", blurb: "Interfaces for testability and extensibility." },
  { section: "Bridge to ASP.NET Core", slug: "14-generics", title: "Generics", blurb: "Type-safe reusable code: List<T>, Repository<T>, constraints." },
  { section: "Bridge to ASP.NET Core", slug: "15-records-null", title: "Records & Null Safety", blurb: "Records for data, and nullable reference types." },
  { section: "Bridge to ASP.NET Core", slug: "16-exceptions", title: "Exceptions", blurb: "try, catch, finally, throw, and custom exceptions." },
  { section: "Bridge to ASP.NET Core", slug: "17-linq", title: "Lambdas & LINQ", blurb: "Func, lambdas, and querying collections." },
  { section: "Bridge to ASP.NET Core", slug: "18-async", title: "Async & Await", blurb: "Task, async, await: doing other work while waiting." },
  { section: "Bridge to ASP.NET Core", slug: "19-web-api", title: "Your First Web API", blurb: "Everything together in a single-file ASP.NET Core API." },
];
